name: CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: 23
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
